sudo: required
language: cpp
dist: trusty

compiler:
  - clang
  - gcc
os:
  - linux

install:  
  - echo $LANG
  - echo $LC_ALL
  - chmod +x ./scripts/dependencies.sh
  - chmod +x ./scripts/build.sh
  - ./scripts/dependencies.sh

script:
  - ./scripts/build.sh